---
title: "MT4113 Lecture 3"
subtitle: "Good Programming Practice"
author: "Eiren Jacobson"
date: "26 September 2018"
output:
  xaringan::moon_reader:
    css: ["default", "metropolis.css", "metropolis-fonts.css"]
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---

# Topics Covered*

- The advantages of using **functions**

--

- Different types of **environments**

--

- Understanding the **scope** of variables

--

- Approaches to **testing and debugging**

--

- Software **design** for statisticians

--

- Coding **conventions and style**

.footnote[**This lecture has been modified from material developed by Eric Rexstad*]

---
class: inverse, center, middle

# Functions

---

# Why use functions?

1. Avoid repeating the same code over and over

2. Self-contained

3. Easier to update and propagate changes

4. Make code more readable

---

class: inverse, center, middle

# Environments

---
class: inverse, center, middle

# Scoping

---

# 1. Name Masking

---

# 2. Functions vs. variables

---

# 3. A fresh start

---

# 4. Dynamic lookup

---
class: inverse, center, middle

# Testing and Debugging

---
class: inverse, center, middle

# Software Design

---
class: inverse, center, middle

# Coding Conventions

---

